# Query INBOVEG


```{r connection and query}
 
connection_inboveg <- connect_inbo_dbase(database_name = "D0010_00_Cydonia")

classif_mhq <- bind_rows(
    inboveg_classification(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland", collect = TRUE),
    inboveg_classification(connection = connection_inboveg, survey_name = "N2000meetnet_Moerassen", collect = TRUE),
    inboveg_classification(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland_BHM", collect = TRUE),
    inboveg_classification(connection = connection_inboveg, survey_name = "N2000meetnet_Moeras_BHM", collect = TRUE),
    inboveg_classification(connection = connection_inboveg, survey_name = "N2000meetnet_Duinen_BHM", collect = TRUE)
) %>%
    select(recording_givid = RecordingGivid, survey = Name, type_observed = Classif, classif_type = ActionGroup, classif_key = ListName, type_cover = Cover) %>%
    filter(classif_type == "N2k") %>%
    select(-classif_type)

header_mhq <- bind_rows(
    inboveg_header(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland", collect = TRUE),
    inboveg_header(connection = connection_inboveg, survey_name = "N2000meetnet_Moerassen", collect = TRUE),
    inboveg_header(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland_BHM", collect = TRUE),
    inboveg_header(connection = connection_inboveg, survey_name = "N2000meetnet_Moeras_BHM", collect = TRUE),
    inboveg_header(connection = connection_inboveg, survey_name = "N2000meetnet_Duinen_BHM", collect = TRUE)) %>%
    select(recording_givid = RecordingGivid, survey = Name, user_reference = UserReference, area = Area, vague_date_begin = VagueDateBegin, vague_date_end = VagueDateEnd)

recordings_mhq <- bind_rows(
    inboveg_recordings(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland", collect = TRUE),
    inboveg_recordings(connection = connection_inboveg, survey_name = "N2000meetnet_Moerassen", collect = TRUE),
    inboveg_recordings(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland_BHM", collect = TRUE),
    inboveg_recordings(connection = connection_inboveg, survey_name = "N2000meetnet_Moeras_BHM", collect = TRUE),
    inboveg_recordings(connection = connection_inboveg, survey_name = "N2000meetnet_Duinen_BHM", collect = TRUE)) %>%
    select(survey = Name, recording_givid = RecordingGivid, layer_code = LayerCode, layer_cover = CoverCode, name_original = OriginalName, name_scientific = ScientificName, phenology_code = PhenologyCode, species_cover_code = CoverageCode, species_cover = PctValue, scale = RecordingScale)

qualifiers_mhq <- bind_rows(inboveg_qualifiers(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland", qualifier_type = "MQ"),
                            inboveg_qualifiers(connection = connection_inboveg, survey_name = "N2000meetnet_Moerassen", qualifier_type = "MQ"),
                            inboveg_qualifiers(connection = connection_inboveg, survey_name = "N2000meetnet_Grasland_BHM", qualifier_type = "MQ"),
                            inboveg_qualifiers(connection = connection_inboveg, survey_name = "N2000meetnet_Moeras_BHM", qualifier_type = "MQ"),
                            inboveg_qualifiers(connection = connection_inboveg, survey_name = "N2000meetnet_Duinen_BHM", qualifier_type = "MQ")) %>%
    select(survey = Name, recording_givid = RecordingGivid, user_reference = UserReference, structure_var_code = Q2Code, structure_var = Q2Description, cover = Q3Description) %>%
    mutate(structure_var_code = tolower(structure_var_code),
           structure_var = tolower(structure_var),
           cover = as.numeric(cover))

```

```{r}
setwd("../../n2khab_mhq_data/field-data/inboveg")
dir.create(as.character(str_c("export_inboveg", as.character(Sys.Date(),"%Y-%m-%d"), sep = "_")))
setwd(str_c("export_inboveg_", as.character(Sys.Date(),"%Y-%m-%d"), "/"))

write.csv2(classif_mhq, "classif_mhq.csv", row.names = FALSE)
write.csv2(header_mhq, "header_mhq.csv", row.names = FALSE)
write.csv2(qualifiers_mhq, "structure_mhq.csv", row.names = FALSE)
write.csv2(recordings_mhq, "vegetation_mhq.csv", row.names = FALSE)
```

