# Query fieldmap

```{r}

db_fieldmap_open_hab <- "../../n2khab_mhq_data/field-data/fieldmap/database_2020-01-31/FieldMapData_NA2000.accdb"

get_status <- function(db = db_fieldmap_open_hab){

query_gridpoints <- "SELECT Grid_points.IDPlots
  , Grid_points.RANKING
  , Grid_points.ID
  , Grid_points.SingleID
  , Grid_points.Status_Fieldwork
  , YesNo.Value1
  , Grid_points.Info_Status_Fieldwork
  , qinfo_Status_Fieldwork.Value1
  , Grid_points.Remark

FROM ((Grid_points LEFT JOIN qFieldteam ON Grid_points.Fieldteam = qFieldteam.ID)
  LEFT JOIN qinfo_Status_Fieldwork ON Grid_points.Info_Status_Fieldwork = qinfo_Status_Fieldwork.ID)
  LEFT JOIN [YesNo] ON Grid_points.Status_Fieldwork = YesNo.ID
;"

  if(substr(db,nchar(db)-3,nchar(db)) == ".mdb"){
    connectieDB <-   odbcConnectAccess(db)
  } else if (substr(db,nchar(db)-5,nchar(db)) == ".accdb") {
    connectieDB <-   odbcConnectAccess2007(db)
  }

 gridpointsOrig <- sqlQuery(connectieDB, query_gridpoints)
  gridPoint <- gridpointsOrig %>%
    select(sample_id = SingleID, grts_ranking = RANKING, status_fieldwork = Value1, info_status_fieldwork = Value1.1, Remark) %>%
    filter(!is.na(status_fieldwork))

  odbcClose(connectieDB)

  return(gridPoint)
}

get_observed_hab <- function (db = db_fieldmap_open_hab){

  query_HabTypeObserved <- "
  SELECT
  Standdescription.IDPlots,
  Standdescription.ID,
  Standdescription.Area_m2,
  Standdescription.HABITAT,
  qHABITAT.Value1
  FROM Standdescription LEFT JOIN qHABITAT ON Standdescription.HABITAT = qHABITAT.ID;
  "

  if(substr(db,nchar(db)-3,nchar(db)) == ".mdb"){
    connectieDB <-   odbcConnectAccess(db)
  } else if (substr(db,nchar(db)-5,nchar(db)) == ".accdb") {
    connectieDB <-   odbcConnectAccess2007(db)
  }

  habObservedOrig <- sqlQuery(connectieDB, query_HabTypeObserved, stringsAsFactors = TRUE)

  odbcClose(connectieDB)

  habObserved <- habObservedOrig %>%
    rename(plot_id = IDPlots,
           segment_id = ID,
           type_observed_code = HABITAT,
           type_observed = Value1) %>%
    mutate(type_observed = gsub(" ", "_", type_observed),
           segment_weight = round(ifelse (is.na(Area_m2),1,Area_m2/(pi*18^2)), 2))

  result <- habObserved

  return (result)
}

get_measurements_square <- function(db = db_fieldmap_open_hab){

  query_CoverPlot <- "
  SELECT
  VegPQ.IDPlots,
  VegPQ.ID,
  VegPQ.HAB1,
  qHABITAT.Value1,
  VegPQ.Licheneslayer,
  VegPQ.Sphagnumlayer,
  VegPQ.OtherMosslayer,
  VegPQ.Herblayer,
  VegPQ.Shrublayer,
  VegPQ.Treelayer,
  VegPQ.Shrub_and_Treelayer,
  VegPQ.Litter
  FROM VegPQ LEFT JOIN qHABITAT ON VegPQ.HAB1 = qHABITAT.ID;"


   if(substr(db,nchar(db)-3,nchar(db)) == ".mdb"){
    connectieDB <-   odbcConnectAccess(db)
  } else if (substr(db,nchar(db)-5,nchar(db)) == ".accdb") {
    connectieDB <-   odbcConnectAccess2007(db)
  }

  coverPlotsOrig <- sqlQuery(connectieDB, query_CoverPlot, stringsAsFactors = FALSE)

  odbcClose(connectieDB)

  coverPlots <- coverPlotsOrig %>%
    mutate(Mosslayer = Sphagnumlayer + OtherMosslayer) %>%
    rename(type_observed_square = Value1, herblayer = Herblayer, shrublayer = Shrublayer, treelayer = Treelayer, shrub_treelayer = Shrub_and_Treelayer, litter = Litter) %>%
    filter(ID == 1) %>%  # een vegetatieopname per plot
    gather(herblayer, shrublayer, treelayer, shrub_treelayer, litter, key = "layer", value = "cover")  %>%
    select(plot_id = IDPlots, type_observed_square, layer, cover) %>%
    mutate(type_observed_square = sub(" ", "_", type_observed_square)) %>%
      arrange(plot_id)

  return(coverPlots)

}


get_cover_species <- function(db = db_fieldmap_open_hab){

  query_herblayer<-"
  SELECT Herblayer.IDPlots,
  Herblayer.Species,
  qVEG_HerbSpecies.Value1,
  qVEG_HerbSpeciesScientific.Value1,
  Herblayer.Coverage_date1,
  qLondo.Value1
  FROM ((Herblayer
  LEFT JOIN qVEG_HerbSpecies ON Herblayer.Species = qVEG_HerbSpecies.ID)
  LEFT JOIN qVEG_HerbSpeciesScientific ON Herblayer.Species_scientific = qVEG_HerbSpeciesScientific.ID)
  LEFT JOIN qLondo ON Herblayer.Coverage_date1 = qLondo.ID;
  "

  query_shrublayer <- "
  SELECT Shrublayer.IDPlots,
  Shrublayer.Species,
  qVEG_TreeSpecies.Value1,
  qVEG_TreeSpeciesScientific.Value1,
  Shrublayer.Coverage,
  qLondo.Value1
  FROM ((Shrublayer
  LEFT JOIN qVEG_TreeSpecies ON Shrublayer.Species = qVEG_TreeSpecies.ID)
  LEFT JOIN qVEG_TreeSpeciesScientific ON Shrublayer.Species_Scientific = qVEG_TreeSpeciesScientific.ID)
  LEFT JOIN qLondo ON Shrublayer.Coverage = qLondo.ID;

  "

  query_treelayer <- "
  SELECT Treelayer.IDPlots,
  Treelayer.Species,
  qVEG_TreeSpecies.Value1,
  qVEG_TreeSpeciesScientific.Value1,
  Treelayer.Coverage,
  qLondo.Value1
  FROM ((Treelayer
  LEFT JOIN qVEG_TreeSpecies ON Treelayer.Species = qVEG_TreeSpecies.ID)
  LEFT JOIN qVEG_TreeSpeciesScientific ON Treelayer.Species_Scientific = qVEG_TreeSpeciesScientific.ID)
  LEFT JOIN qLondo ON Treelayer.Coverage = qLondo.ID;
  "

  query_mosslayer <- "
  SELECT Mosslayer.IDPlots,
  Mosslayer.Species,
  qVEG_MossSpecies.Value1,
  qVEG_MossSpeciesScientific.Value1,
  Mosslayer.Coverage,
  qLondo.Value1
  FROM ((Mosslayer
  LEFT JOIN qVEG_MossSpecies ON Mosslayer.Species = qVEG_MossSpecies.ID)
  LEFT JOIN qVEG_MossSpeciesScientific ON Mosslayer.Species_Scientific = qVEG_MossSpeciesScientific.ID)
  LEFT JOIN qLondo ON Mosslayer.Coverage = qLondo.ID;
  "

  if(substr(db,nchar(db)-3,nchar(db)) == ".mdb"){
    connectieDB <-   odbcConnectAccess(db)
  } else if (substr(db,nchar(db)-5,nchar(db)) == ".accdb") {
    connectieDB <-   odbcConnectAccess2007(db)
  }

  herblayerOrig <- sqlQuery(connectieDB, query_herblayer, stringsAsFactors = FALSE)
  shrublayerOrig <- sqlQuery(connectieDB, query_shrublayer, stringsAsFactors = FALSE)
  treelayerOrig <- sqlQuery(connectieDB, query_treelayer, stringsAsFactors = FALSE)
  mosslayerOrig <- sqlQuery(connectieDB, query_mosslayer, stringsAsFactors = FALSE)

  odbcClose(connectieDB)

   herblayer <- herblayerOrig %>%
     filter(!is.na(Species)) %>%
     select(plot_id = IDPlots,  name_nl = Value1, name_sc = Value1.1,  cover_class = Value1.2) %>%
     mutate(layer = "herblayer")

   shrublayer <- shrublayerOrig %>%
     filter(!is.na(Species)) %>%
     select(plot_id = IDPlots,  name_nl = Value1, name_sc = Value1.1, cover_class = Value1.2) %>%
     mutate(layer = "shrublayer")

   treelayer <- treelayerOrig %>%
     filter(!is.na(Species)) %>%
     select(plot_id = IDPlots,  name_nl = Value1, name_sc = Value1.1,  cover_class = Value1.2) %>%
     mutate(layer = "treelayer")

   mosslayer <- mosslayerOrig %>%
     filter(!is.na(Species)) %>%
     select(plot_id = IDPlots, name_nl = Value1, name_sc = Value1.1, cover_class = Value1.2) %>%
     mutate(layer = "mosslayer")

  veglayers <- bind_rows(herblayer, shrublayer, treelayer, mosslayer) %>%
    mutate(scale = "Londo") %>%
    arrange(plot_id, layer, name_sc)
    
  return(veglayers)

}

get_measurements_heath_circle <- function(db = db_fieldmap_open_hab){

  query_StructurePlotHeide <- "SELECT
  SiteDescription_HEIDE.IDPlots,
SiteDescription_HEIDE.Edit_date,
  SiteDescription_HEIDE.Shrub_and_Treelayer_18m,
  SiteDescription_HEIDE.Sphagnumlayer,
  SiteDescription_HEIDE.Campylopus_introflexus,
  SiteDescription_HEIDE.LowShrublayer,
  SiteDescription_HEIDE.Brushwood,
  SiteDescription_HEIDE.Herbs,
  SiteDescription_HEIDE.Calluna_phase_pioneer,
  SiteDescription_HEIDE.Calluna_phase_devel,
  SiteDescription_HEIDE.Calluna_phase_climax,
  SiteDescription_HEIDE.Calluna_phase_degen,
  SiteDescription_HEIDE.Pioneer_phase_open_soil,
  SiteDescription_HEIDE.Pioneer_Coryn_Aira,
  SiteDescription_HEIDE.Pioneer_Mos,
  SiteDescription_HEIDE.Pioneer_Lichenen
  FROM SiteDescription_HEIDE;"
  
  query_scale_tansley <- "SELECT
  qCoverageTansley.ID,
  qCoverageTansley.Value1
  FROM qCoverageTansley;"

  if(substr(db,nchar(db)-3,nchar(db)) == ".mdb"){
    connectieDB <-   odbcConnectAccess(db)
  } else if (substr(db,nchar(db)-5,nchar(db)) == ".accdb") {
    connectieDB <-   odbcConnectAccess2007(db)
  }

  structurePlots <- sqlQuery(connectieDB, query_StructurePlotHeide, stringsAsFactors = FALSE)

  scale_tansley <- sqlQuery(connectieDB, query_scale_tansley, stringsAsFactors = FALSE)

  odbcClose(connectieDB)

# uitgezonderd bedekking van struik+boomlaag worden alle bedekkingen via Tansley-schaal bepaald
  structurePlots_Tansley <- structurePlots %>%
    select(-Shrub_and_Treelayer_18m) %>%
    gather(-IDPlots, -Edit_date, key = "structure_var", value = "ID") %>%
    mutate(scale = "Beheermonitoringsschaal") %>%
      left_join(scale_tansley, by = "ID") %>%
      select(plot_id = IDPlots, structure_var, cover_class = Value1, scale) %>%
      mutate(structure_var = tolower(structure_var))
  
  structurePlots_Cover <- structurePlots %>%
      mutate(structure_var = "shrub_treelayer") %>%
      select(plot_id = IDPlots, structure_var, cover = Shrub_and_Treelayer_18m)
      

# alle records als bedekking uitgedrukt
  structurePlots_cover_long <- bind_rows(structurePlots_Tansley,
                                   structurePlots_Cover) %>%
      arrange(plot_id, structure_var)

  return(structurePlots_cover_long)

}

get_measurements_6510_circle <- function(db = db_fieldmap_open_hab){

  query_StructurePlot6510 <- "SELECT
  SiteDescription_6510.IDPlots,
  SiteDescription_6510.Shrub_and_Treelayer_18m
  FROM SiteDescription_6510"

     if(substr(db,nchar(db)-3,nchar(db)) == ".mdb"){
    connectieDB <-   odbcConnectAccess(db)
  } else if (substr(db,nchar(db)-5,nchar(db)) == ".accdb") {
    connectieDB <-   odbcConnectAccess2007(db)
  }

  structurePlots <- sqlQuery(connectieDB, query_StructurePlot6510) %>%
      mutate(structure_var = "shrub_treelayer") %>%
      select(plot_id = IDPlots, structure_var, cover = Shrub_and_Treelayer_18m)

  odbcClose(connectieDB)
  
  return(structurePlots)
}

get_observation_date <- function(db = db_fieldmap_open_hab){

  query_date <- "SELECT
  Observer_date.IDPlots,
  Observer_date.Starting_time
  FROM Observer_date"

     if(substr(db,nchar(db)-3,nchar(db)) == ".mdb"){
    connectieDB <-   odbcConnectAccess(db)
  } else if (substr(db,nchar(db)-5,nchar(db)) == ".accdb") {
    connectieDB <-   odbcConnectAccess2007(db)
  }

  observer_date <- sqlQuery(connectieDB, query_date) %>%
      select(plot_id = IDPlots, date = Starting_time)

  odbcClose(connectieDB)
  
  return(observer_date)
}

```



```{r}

sample_status <- get_status()
hab_observed <- get_observed_hab()
measurements_square <- get_measurements_square()
cover_species <- get_cover_species()
measurements_heath_circle <- get_measurements_heath_circle() 
measurements_6510_circle <- get_measurements_6510_circle()
observer_date <- get_observation_date()


setwd("../../n2khab_mhq_data/field-data/fieldmap/")
dir.create(as.character(str_c("export_fieldmap", as.character(Sys.Date(),"%Y-%m-%d"), sep = "_")))
setwd(str_c("export_fieldmap_", as.character(Sys.Date(),"%Y-%m-%d"), "/"))

write.csv2(sample_status, "sample_status.csv", row.names = FALSE)
write.csv2(hab_observed, "hab_observed.csv", row.names = FALSE)
write.csv2(measurements_square, "measurements_square.csv", row.names = FALSE)
write.csv2(cover_species, "cover_species.csv", row.names = FALSE)
write.csv2(measurements_heath_circle, "measurements_heath_circle.csv", row.names = FALSE)
write.csv2(measurements_6510_circle, "measurements_6510_circle.csv", row.names = FALSE)
write.csv2(observer_date, "observer_date.csv", row.names = FALSE)

```

