# Generate mhq sample admin table


## read INBO admin data

```{r}

admin_inbo_orig <- read.csv2("../../n2khab_mhq_data/10_raw/admin/inbo/meetnet_2020.csv")

admin_inbo <- admin_inbo_orig %>%
    mutate(visit_status = ifelse(bezocht > 0, "visited", "not visited"),
           visit_status = factor(visit_status, levels = c("visited", "not visited", "inaccessable")),
           measured = !is.na(opname) & opname == "ja",
           position_change = !is.na(verplaatst) & verplaatst == "ja",
           visit_year = ifelse(visit_status == "visited", bezocht, NA),
           visit_year = ifelse(visit_year == 19, 2019, visit_year)) %>%
    select(sample_id = ID, visit_status, visit_year, measured, position_change, x_measured = POINT_X, y_measured = POINT_Y)

```


## Read INBO field measurements

```{r}


classif_mhq <- read.csv2("../../n2khab_mhq_data/10_raw/field-data/moeras-grasland/inboveg_2020-03-04/classif_mhq.csv")
header_mhq <- read.csv2("../../n2khab_mhq_data/10_raw/field-data/moeras-grasland/inboveg_2020-03-04/header_mhq.csv")
recordings_mhq <- read.csv2("../../n2khab_mhq_data/10_raw/field-data/moeras-grasland/inboveg_2020-03-04/header_mhq.csv")

classif_mhq_type <- classif_mhq %>%
  filter(classif_type == "N2k") %>%
  select(recording_givid, hab_observed = classif, segment_weight = cover) %>%
  mutate(segment_weight = as.numeric(segment_weight))

segments <- header_mhq %>%
  mutate(plot = ifelse(area == 1017 & !is.na(area), "circle", "square")) %>%
  select(recording_givid, grts_ranking = user_reference, plot, date = vague_date_begin) %>%
  full_join(classif_mhq_type, by = "recording_givid") %>%
  mutate(data_imported = recording_givid %in% recordings_mhq$recording_givid) %>%
    left_join(select(samples, grts_ranking, sample_id = id, main_type, type), by = "grts_ranking") %>%
    mutate(hab_observed = ifelse(hab_observed == "6410" & main_type == "6410", as.character(type), hab_observed),
           hab_observed = ifelse(hab_observed == "6230" & main_type == "6230", as.character(type), hab_observed),
           hab_observed = ifelse(hab_observed %in% c("-9", "0"), "gh", hab_observed),
           is_type_target = hab_observed == type,
           is_main_type_target = str_sub(hab_observed, 1, 4) == main_type) %>%
    group_by(grts_ranking, plot, date) %>%
    mutate(is_type_target_plot = sum(is_type_target) > 0,
           is_main_type_target_plot = sum(is_main_type_target) > 0,
           n_habtarget = n_distinct(type),
           n_segments = n_distinct(hab_observed)) %>%
    ungroup() %>%
    group_by(sample_id, plot, date) %>%
    mutate(cover_description = str_c(str_c(segment_weight, "% ", hab_observed), collapse =  " + ")) %>%
    ungroup()

segments_check <- segments %>%
    filter(n_segments > 1,
           plot == "square",
           ) %>%
    select(recording_givid, sample_id, plot_bevat_doelhabitat = is_type_target_plot, date, hab_target = type, hab_observed, cover = segment_weight, n_segments) %>%
    arrange(sample_id) %>%
    filter(hab_target != "6510_hu") %>%
    arrange(plot_bevat_doelhabitat) 

segments_doubles_check <- segments %>%
    filter(plot == "square") %>%
    group_by(sample_id) %>%
    mutate(n_dates = n_distinct(date)) %>%
    ungroup() %>%
    filter(n_dates > 1) %>%
    distinct(recording_givid, grts_ranking, date, hab_observed, segment_weight) %>%
    arrange(grts_ranking)

write.csv2(segments_check, "../../output/pq_mixed_cover.csv", row.names = FALSE)

write.csv2(segments_doubles_check, "../../output/pq_dubbels.csv", row.names = FALSE)

segments_center <- segments %>%
    filter(plot == "square") %>%
    mutate(segment_center = ifelse(n_segments <= 1 , TRUE,
                                   ifelse(is_type_target_plot, is_type_target, is_main_type_target))) %>%
    distinct(date, grts_ranking, hab_observed,  segment_center) %>% 
    group_by(grts_ranking, date) %>%
           mutate(n_center = sum(segment_center, na.rm = TRUE)) %>%
    ungroup()
              
# assessment_square <- assessment %>%
#     filter(plot == "square")
    
```


```{r}

```






```{r}
sample_admin_grassland_marshes <- admin_inbo %>% 
    left_join(assessment_square, by = "sample_id")
```





## Read ANB admin data

```{r}

admin_anb_orig <- read.csv2("../../data/admin/anb/PlotsMetDataAFGEWERKT.csv")

admin_anb <- admin_anb_orig %>%
    mutate(circleplot_measured = ifelse(!is.na(Sitedescr_6510), Sitedescr_6510,
                                        ifelse(!is.na(Sitedescr_heide), Sitedescr_heide, NA))) %>%
    select(id = SingleID, obs_circleplot = Hab_Standdesc, obs_vegplot = hab_VegPQ, vegplot_measured = VEGPQ, circleplot_measured, notes = opm_navplot) %>%
    mutate(obs_vegplot = ifelse(obs_vegplot != "geen habitat (akker, houtkant, tuin,...)", 
                                str_replace(obs_vegplot, " ", "_"),
                                obs_vegplot),
           obs_circleplot = ifelse(obs_circleplot != "geen habitat (akker, houtkant, tuin,...)", 
                                str_replace(obs_circleplot, " ", "_"),
                                obs_circleplot))

```
