# Scales used for vegetation assessments

```{r, eval=FALSE}

# only run when original file changes

scales_orig <- read.csv2("../../mhq_sample-admin_data/original/scales/Schalen.csv", stringsAsFactors = FALSE)

scales <- scales_orig %>%
    rename(coverscale_name = Schaal,
           class_id = KlasseID,
           class_code = KlasseCode,
           cover_description = KlasseBeschrijving,
           cover_mean = BedekkingGem,
           cover_min = BedekkingMin,
           cover_max = BedekkingMax) %>%
    mutate(class_code = ifelse(class_code == "", NA, class_code))

#write_vc(scales, file = "coverscales_mhq", root = "../../data", sorting = c("coverscale_name", "class_id"), strict = FALSE)
```


# Functions to access open habitat fieldmap database


```{r}

get_status_openhab <- function(db = db_fieldmap_openhab){

query_gridpoints <- "SELECT Grid_points.Ranking as plot_id
  , Grid_points.Add_date as date_satus
  , Grid_points.SingleID as sampling_unit_code
  , YesNo.Value1 as status_fieldwork
  , qinfo_Status_Fieldwork.Value1 as info_status_fieldwork
  , Grid_points.Remark as remark

FROM ((Grid_points LEFT JOIN qFieldteam ON Grid_points.Fieldteam = qFieldteam.ID)
  LEFT JOIN qinfo_Status_Fieldwork ON Grid_points.Info_Status_Fieldwork = qinfo_Status_Fieldwork.ID)
  LEFT JOIN [YesNo] ON Grid_points.Status_Fieldwork = YesNo.ID
;"

  if (str_sub(db, nchar(db) - 3, nchar(db)) == ".mdb") {
    connect_db <-   odbcConnectAccess(db)
  } else if (str_sub(db, nchar(db) - 5, nchar(db)) == ".accdb") {
    connect_db <-   odbcConnectAccess2007(db)
  } else if (str_sub(db, nchar(db) - 3, nchar(db)) == ".FDB") {
    connect_db <-   odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))
  }

 gridpoints_orig <- sqlQuery(connect_db, query_gridpoints)
  gridpoints <- gridpoints_orig %>%
    filter(!is.na(status_fieldwork))

  odbcClose(connect_db)

  return(gridpoints)
}

get_type_observed_openhab <- function(db = db_fieldmap_openhab){

  query_type_observed_circle <- "
  SELECT
  Standdescription.IDPlots as plot_id,
  Standdescription.ID as segment_id,
  Standdescription.Add_date as date_standdescription,
  Standdescription.Area_m2 as area_m2,
  qHABITAT.Value1 as type_observed_circle
  FROM Standdescription LEFT JOIN qHABITAT ON Standdescription.HABITAT = qHABITAT.ID;
  "
  
  query_type_observed_square <- "
  SELECT
  VegPQ.IDPlots as plot_id,
  qHABITAT.Value1 as type_observed_square
  FROM VegPQ LEFT JOIN qHABITAT ON VegPQ.HAB1 = qHABITAT.ID;
  "

  if (str_sub(db, nchar(db) - 3, nchar(db)) == ".mdb") {
    connect_db <-   odbcConnectAccess(db)
  } else if (str_sub(db, nchar(db) - 5, nchar(db)) == ".accdb") {
    connect_db <-   odbcConnectAccess2007(db)
  } else if (str_sub(db, nchar(db) - 3, nchar(db)) == ".FDB") {
    connect_db <-   odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))
  }

  type_observed_circle_orig <- sqlQuery(connect_db, query_type_observed_circle, stringsAsFactors = FALSE)
  type_observed_square_orig <- sqlQuery(connect_db, query_type_observed_square, stringsAsFactors = FALSE)
  
  odbcClose(connect_db)

  type_observed_square <- type_observed_square_orig %>%
      filter(!is.na(type_observed_square))
  
  type_observed <- type_observed_circle_orig %>%
    full_join(type_observed_square, by = c("plot_id")) %>%
    mutate(type_observed_circle = ifelse(nchar(type_observed_circle) %in% c(7, 8),
                                         gsub(" ", "_", type_observed_circle),
                                         type_observed_circle),
           type_observed_square = ifelse(nchar(type_observed_square) %in% c(7, 8),
                                         gsub(" ", "_", type_observed_square),
                                         type_observed_square),
           type_observed_cover_circle = round(ifelse (is.na(area_m2),1,area_m2/(pi*18^2)), 2))

  result <- type_observed

  return(result)
}

get_cover_veglayers_openhab <- function(db = db_fieldmap_openhab){

  query_cover_veglayers <- "
  SELECT
  VegPQ.IDPlots as plot_id,
  VegPQ.ID as segment_id,
  VegPQ.Licheneslayer,
  VegPQ.Sphagnumlayer,
  VegPQ.OtherMosslayer,
  VegPQ.Herblayer,
  VegPQ.Shrublayer,
  VegPQ.Treelayer,
  VegPQ.Shrub_and_Treelayer as shrub_treelayer,
  VegPQ.Litter
  FROM VegPQ;"

  if (str_sub(db, nchar(db) - 3, nchar(db)) == ".mdb") {
    connect_db <-   odbcConnectAccess(db)
  } else if (str_sub(db, nchar(db) - 5, nchar(db)) == ".accdb") {
    connect_db <-   odbcConnectAccess2007(db)
  } else if (str_sub(db, nchar(db) - 3, nchar(db)) == ".FDB") {
    connect_db <-   odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))
  }

  cover_veglayers_orig <- sqlQuery(connect_db, query_cover_veglayers, stringsAsFactors = FALSE)
  
  odbcClose(connect_db)

  colnames(cover_veglayers_orig) <- str_to_lower(colnames(cover_veglayers_orig))
  
  cover_veglayers <- cover_veglayers_orig %>%
    mutate(mosslayer = sphagnumlayer + othermosslayer) %>%
    gather(mosslayer, herblayer, shrublayer, treelayer, shrub_treelayer, licheneslayer, sphagnumlayer, othermosslayer, litter, key = "layer", value = "cover") %>%
    arrange(plot_id)

  return(cover_veglayers)

}


get_cover_species_openhab <- function(db = db_fieldmap_openhab){

  query_herblayer<-"
  SELECT Herblayer.IDPlots as plot_id,
  Herblayer.Species as name_id,
  qVEG_HerbSpecies.Value1 as name_nl,
  qVEG_HerbSpeciesScientific.Value1 as name_sc,
  Herblayer.Coverage_date1 as class_id,
  qLondo.Value1 as cover_description
  FROM ((Herblayer
  LEFT JOIN qVEG_HerbSpecies ON Herblayer.Species = qVEG_HerbSpecies.ID)
  LEFT JOIN qVEG_HerbSpeciesScientific ON Herblayer.Species_scientific = qVEG_HerbSpeciesScientific.ID)
  LEFT JOIN qLondo ON Herblayer.Coverage_date1 = qLondo.ID;
  "

  query_shrublayer <- "
  SELECT Shrublayer.IDPlots as plot_id,
  Shrublayer.Species as name_id,
  qVEG_TreeSpecies.Value1 as name_nl,
  qVEG_TreeSpeciesScientific.Value1 as name_sc,
  Shrublayer.Coverage as class_id,
  qLondo.Value1 as cover_description
  FROM ((Shrublayer
  LEFT JOIN qVEG_TreeSpecies ON Shrublayer.Species = qVEG_TreeSpecies.ID)
  LEFT JOIN qVEG_TreeSpeciesScientific ON Shrublayer.Species_Scientific = qVEG_TreeSpeciesScientific.ID)
  LEFT JOIN qLondo ON Shrublayer.Coverage = qLondo.ID;

  "

  query_treelayer <- "
  SELECT Treelayer.IDPlots as plot_id,
  Treelayer.Species as name_id,
  qVEG_TreeSpecies.Value1 as name_nl,
  qVEG_TreeSpeciesScientific.Value1 as name_sc,
  Treelayer.Coverage as class_id,
  qLondo.Value1 as cover_description
  FROM ((Treelayer
  LEFT JOIN qVEG_TreeSpecies ON Treelayer.Species = qVEG_TreeSpecies.ID)
  LEFT JOIN qVEG_TreeSpeciesScientific ON Treelayer.Species_Scientific = qVEG_TreeSpeciesScientific.ID)
  LEFT JOIN qLondo ON Treelayer.Coverage = qLondo.ID;
  "

  query_mosslayer <- "
  SELECT Mosslayer.IDPlots as plot_id,
  Mosslayer.Species as name_id,
  qVEG_MossSpecies.Value1 as name_nl,
  qVEG_MossSpeciesScientific.Value1 as name_sc,
  Mosslayer.Coverage as class_id,
  qLondo.Value1 as cover_description
  FROM ((Mosslayer
  LEFT JOIN qVEG_MossSpecies ON Mosslayer.Species = qVEG_MossSpecies.ID)
  LEFT JOIN qVEG_MossSpeciesScientific ON Mosslayer.Species_Scientific = qVEG_MossSpeciesScientific.ID)
  LEFT JOIN qLondo ON Mosslayer.Coverage = qLondo.ID;
  "

  if (str_sub(db, nchar(db) - 3, nchar(db)) == ".mdb") {
    connect_db <-   odbcConnectAccess(db)
  } else if (str_sub(db, nchar(db) - 5, nchar(db)) == ".accdb") {
    connect_db <-   odbcConnectAccess2007(db)
  } else if (str_sub(db, nchar(db) - 3, nchar(db)) == ".FDB") {
    connect_db <-   odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))
  }

  herblayer_orig <- sqlQuery(connect_db, query_herblayer, stringsAsFactors = FALSE)
  shrublayer_orig <- sqlQuery(connect_db, query_shrublayer, stringsAsFactors = FALSE)
  treelayer_orig <- sqlQuery(connect_db, query_treelayer, stringsAsFactors = FALSE)
  mosslayer_orig <- sqlQuery(connect_db, query_mosslayer, stringsAsFactors = FALSE)

  odbcClose(connect_db)

   herblayer <- herblayer_orig %>%
     mutate(layer = "herblayer")

   shrublayer <- shrublayer_orig %>%
     mutate(layer = "shrublayer")

   treelayer <- treelayer_orig %>%
     mutate(layer = "treelayer")

   mosslayer <- mosslayer_orig %>%
     mutate(layer = "mosslayer")

  coverscales <- read_vc(file = "coverscales_mhq", root = "../../data")
   
  veglayers <- bind_rows(herblayer, shrublayer, treelayer, mosslayer) %>%
    filter(!is.na(name_id)) %>%
    mutate(coverscale_name = "Londo") %>%
    left_join(coverscales, by = c("coverscale_name", "class_id", "cover_description")) %>%
    select(plot_id, layer, name_nl, name_sc, coverscale_name, cover_description, cover_mean) %>%
    arrange(plot_id, layer, name_sc)
    
  return(veglayers)

}

get_measurements_heath_circle <- function(db = db_fieldmap_openhab){

  query_structurevar_heath<- "SELECT
  SiteDescription_HEIDE.IDPlots as plot_id,
SiteDescription_HEIDE.Edit_date as date_sitedescription,
  SiteDescription_HEIDE.Shrub_and_Treelayer_18m,
  SiteDescription_HEIDE.Sphagnumlayer,
  SiteDescription_HEIDE.Campylopus_introflexus,
  SiteDescription_HEIDE.LowShrublayer,
  SiteDescription_HEIDE.Brushwood,
  SiteDescription_HEIDE.Herbs,
  SiteDescription_HEIDE.Calluna_phase_pioneer,
  SiteDescription_HEIDE.Calluna_phase_devel,
  SiteDescription_HEIDE.Calluna_phase_climax,
  SiteDescription_HEIDE.Calluna_phase_degen,
  SiteDescription_HEIDE.Pioneer_phase_open_soil,
  SiteDescription_HEIDE.Pioneer_Coryn_Aira,
  SiteDescription_HEIDE.Pioneer_Mos,
  SiteDescription_HEIDE.Pioneer_Lichenen
  FROM SiteDescription_HEIDE;"
  

  if (str_sub(db, nchar(db) - 3, nchar(db)) == ".mdb") {
    connect_db <-   odbcConnectAccess(db)
  } else if (str_sub(db, nchar(db) - 5, nchar(db)) == ".accdb") {
    connect_db <-   odbcConnectAccess2007(db)
  } else if (str_sub(db, nchar(db) - 3, nchar(db)) == ".FDB") {
    connect_db <-   odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))
  }

  structure_vars <- sqlQuery(connect_db, query_structurevar_heath, stringsAsFactors = FALSE)

  odbcClose(connect_db)
  
  coverscales <- read_vc(file = "coverscales_mhq", root = "../../data")

# uitgezonderd bedekking van struik+boomlaag worden alle bedekkingen via BMS-schaal bepaald
  structure_var_bms <- structure_vars %>%
    select(-Shrub_and_Treelayer_18m) %>%
    gather(-plot_id, -date_sitedescription, key = "structure_var", value = "class_id") %>%
    mutate(coverscale_name = "Beheermonitoringsschaal") %>%
      left_join(coverscales, by = c("coverscale_name","class_id")) %>%
      select(plot_id, structure_var, coverscale_name, cover_description, cover_mean) %>%
      mutate(structure_var = tolower(structure_var))
  
  structure_var_cover <- structure_vars %>%
      mutate(structure_var = "shrub_treelayer") %>%
      select(plot_id, structure_var, cover = Shrub_and_Treelayer_18m)
      

# alle records als bedekking uitgedrukt
  structure_vars_long <- bind_rows(structure_var_bms,
                                   structure_var_cover) %>%
      arrange(plot_id, structure_var)

  return(structure_vars_long)

}


get_measurements_heath_circle_old <- function(db = db_fieldmap_openhab){

  query_structurevar_heath<- "SELECT
  SiteDescription_HEIDE.IDPlots as plot_id,
  SiteDescription_HEIDE.Shrub_and_Treelayer_18m,
  SiteDescription_HEIDE.Sphagnumlayer,
  SiteDescription_HEIDE.Campylopus_introflexus,
  SiteDescription_HEIDE.LowShrublayer,
  SiteDescription_HEIDE.Brushwood,
  SiteDescription_HEIDE.Herbs,
  SiteDescription_HEIDE.Calluna_phase_pioneer,
  SiteDescription_HEIDE.Calluna_phase_devel,
  SiteDescription_HEIDE.Calluna_phase_climax,
  SiteDescription_HEIDE.Calluna_phase_degen,
  SiteDescription_HEIDE.Pioneer_phase_open_soil,
  SiteDescription_HEIDE.Pioneer_Coryn_Aira,
  SiteDescription_HEIDE.Pioneer_Mos,
  SiteDescription_HEIDE.Pioneer_Lichenen
  FROM SiteDescription_HEIDE;"
  

  if (str_sub(db, nchar(db) - 3, nchar(db)) == ".mdb") {
    connect_db <-   odbcConnectAccess(db)
  } else if (str_sub(db, nchar(db) - 5, nchar(db)) == ".accdb") {
    connect_db <-   odbcConnectAccess2007(db)
  } else if (str_sub(db, nchar(db) - 3, nchar(db)) == ".FDB") {
    connect_db <-   odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))
  }

  structure_vars <- sqlQuery(connect_db, query_structurevar_heath, stringsAsFactors = FALSE)

  odbcClose(connect_db)
  
  coverscales <- read_vc(file = "coverscales_mhq", root = "../../data")
  
# uitgezonderd bedekking van struik+boomlaag worden alle bedekkingen via BMS-schaal bepaald
  structure_var_tansley <- structure_vars %>%
    select(plot_id, LowShrublayer, starts_with("Calluna")) %>%
    gather(-plot_id, key = "structure_var", value = "class_id") %>%
    mutate(coverscale_name = "Tansley") %>%
    left_join(coverscales, by = c("coverscale_name","class_id")) %>%
    select(plot_id, structure_var, coverscale_name, cover_description, cover_mean) %>%
    mutate(structure_var = tolower(structure_var))
  
  structure_var_cover <- structure_vars %>%
    select(-LowShrublayer, -starts_with("Calluna")) %>%
    gather(-plot_id, key = "structure_var", value = "cover")
      

# alle records als bedekking uitgedrukt
  structure_vars_long <- bind_rows(structure_var_tansley,
                                   structure_var_cover) %>%
      arrange(plot_id, structure_var)

  return(structure_vars_long)

}


get_measurements_6510_circle <- function(db = db_fieldmap_openhab){

  query_StructurePlot6510 <- "SELECT
  SiteDescription_6510.IDPlots as plot_id,
  SiteDescription_6510.Shrub_and_Treelayer_18m
  FROM SiteDescription_6510"

   if (str_sub(db, nchar(db) - 3, nchar(db)) == ".mdb") {
    connect_db <-   odbcConnectAccess(db)
  } else if (str_sub(db, nchar(db) - 5, nchar(db)) == ".accdb") {
    connect_db <-   odbcConnectAccess2007(db)
  } else if (str_sub(db, nchar(db) - 3, nchar(db)) == ".FDB") {
    connect_db <-   odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))
  }

  structure_vars <- sqlQuery(connect_db, query_StructurePlot6510) %>%
      mutate(structure_var = "shrub_treelayer") %>%
      select(plot_id , structure_var, cover = Shrub_and_Treelayer_18m)

  odbcClose(connect_db)
  
  return(structure_vars)
}

get_date_openhab <- function(db = db_fieldmap_openhab){

  query_date <- "SELECT
  Observer_date.IDPlots as plot_id,
  Observer_date.Add_date as date_assessment
  FROM Observer_date"

   if (str_sub(db, nchar(db) - 3, nchar(db)) == ".mdb") {
    connect_db <-   odbcConnectAccess(db)
  } else if (str_sub(db, nchar(db) - 5, nchar(db)) == ".accdb") {
    connect_db <-   odbcConnectAccess2007(db)
  } else if (str_sub(db, nchar(db) - 3, nchar(db)) == ".FDB") {
    connect_db <-   odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))
  }

  observer_date <- sqlQuery(connect_db, query_date) %>%
      mutate(date_assessment = as.Date(date_assessment, format = "%Y-%m-%d"))
  
  odbcClose(connect_db)
  
  return(observer_date)
}

get_coordinates_openhab <- function(db = db_fieldmap_openhab){

  query_coord <- "SELECT
  GPS_REF.SingleID as plot_id,
  GPS_REF.X_m as x_measured,
  GPS_REF.Y_m as y_measured
  FROM GPS_REF"

    if (str_sub(db, nchar(db) - 3, nchar(db)) == ".mdb") {
    connect_db <-   odbcConnectAccess(db)
  } else if (str_sub(db, nchar(db) - 5, nchar(db)) == ".accdb") {
    connect_db <-   odbcConnectAccess2007(db)
  } else if (str_sub(db, nchar(db) - 3, nchar(db)) == ".FDB") {
    connect_db <-   odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))
  }

  coordinates <- sqlQuery(connect_db, query_coord) %>%
      filter(!is.na(plot_id))

  odbcClose(connect_db)
  
  return(coordinates)
}

```

# Functions to access forest hab fieldmap database

```{r}

get_status_foresthab <- function(db = db_fieldmap_foresthab){

query_status <- "SELECT G.idplots,
        G.plot_id, 
        G.add_date AS date_status,
        G.status_fieldwork, 
        Q.value1 AS info_status_fieldwork,
        G.veg_done, 
        G.reg_done, 
        G.dendro_done, 
        G.info_springveg, 
        G.springveg, 
        G.remark, 
        G.remark4 
        FROM grid_points G
        LEFT JOIN qinfo_status_fieldwork Q
        ON G.info_status_fieldwork = Q.id"    

connect_db <- odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db_fieldmap_foresthab))

gridpoints_orig <- sqlQuery(connect_db, query_status)
colnames(gridpoints_orig) <- str_to_lower(colnames(gridpoints_orig))

gridpoints <- gridpoints_orig %>%
    filter(!is.na(status_fieldwork)) %>%
    mutate(status_fieldwork = ifelse(status_fieldwork == 0, "nee", 
                                     ifelse(status_fieldwork == 1, "ja")))

odbcClose(connect_db)

return(gridpoints)
}

get_type_observed_foresthab <- function(db = db_fieldmap_foresthab){

  query_type_observed <- "
  SELECT Standdescription_segments.IDPlots as plot_id,
  Standdescription_segments.ID as segment_id,
  Standdescription_segments.Area_m2,
  Standdescription_segments.Add_date as date_standdescription,
  qHABITAT.Value1 as type_observed_circle,
  qLanduse.Value1 as landuse
  FROM Standdescription_segments 
  LEFT JOIN qHABITAT ON Standdescription_segments.HAB = qHABITAT.ID 
  LEFT JOIN qLanduse ON Standdescription_segments.Landuse = qLanduse.ID;
  "

 connect_db <- odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))

 type_observed_orig <- sqlQuery(connect_db, query_type_observed, stringsAsFactors = FALSE)

  odbcClose(connect_db)

  colnames(type_observed_orig) <- str_to_lower(colnames(type_observed_orig))
  
  type_observed <- type_observed_orig %>%
    mutate(type_observed_circle = ifelse(nchar(type_observed_circle) %in% c(7, 8),
                                         gsub(" ", "_", type_observed_circle),
                                         type_observed_circle),
           type_observed_cover_circle = round(ifelse (is.na(area_m2),1,area_m2/(pi*18^2)), 2))

  result <- type_observed

  return(result)
}

get_cover_veglayers_foresthab <- function(db = db_fieldmap_foresthab){

  query_veglayers <- "SELECT
  Vegetation.IDPlots as plot_id,
  Vegetation.ID as segment_id,
  Vegetation.Total_herb_cover as herblayer,
  Vegetation.Total_moss_cover as mosslayer,
  Vegetation.Total_shrub_cover as shrublayer,
  Vegetation.Total_tree_cover as treelayer
  FROM Vegetation;"

  connect_db <- odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))

  veglayers_orig <- sqlQuery(connect_db, query_veglayers, stringsAsFactors = FALSE)

  odbcClose(connect_db)

  colnames(veglayers_orig) <- str_to_lower(colnames(veglayers_orig))
  
  coverscales <- read_vc(file = "coverscales_mhq", root = "../../data")
  
  veglayers <- veglayers_orig %>%
    gather(herblayer, shrublayer, treelayer, mosslayer, key = "layer", value = "class_id") %>%
    mutate(coverscale_name = "CoverVeglayers") %>%
    left_join(coverscales, by = c("coverscale_name", "class_id")) %>%
    select(plot_id, segment_id, layer, cover_description, cover_mean) %>%
    arrange(plot_id, segment_id) 
  
  return(veglayers)

}

get_cover_species_foresthab <- function(db = db_fieldmap_foresthab){

  query_herblayer<-"SELECT Herblayer.IDPlots as plot_id,
  Herblayer.Species as name_id,
  qVEG_HerbSpecies.Value1 as name_nl,
  qVEG_HerbSpeciesScientific.Value1 as name_sc,
  Herblayer.Coverage_date1 as class_id
  FROM Herblayer
  LEFT JOIN qVEG_HerbSpecies ON Herblayer.Species = qVEG_HerbSpecies.ID
  LEFT JOIN qVEG_HerbSpeciesScientific ON Herblayer.Species_scientific = qVEG_HerbSpeciesScientific.ID;
  "

  query_shrublayer <- "
  SELECT Shrublayer.IDPlots as plot_id,
  Shrublayer.Species as name_id,
  qVEG_TreeSpecies.Value1 as name_nl,
  qVEG_TreeSpeciesScientific.Value1 as name_sc,
  Shrublayer.Coverage as class_id
  FROM Shrublayer
  LEFT JOIN qVEG_TreeSpecies ON Shrublayer.Species = qVEG_TreeSpecies.ID
  LEFT JOIN qVEG_TreeSpeciesScientific ON Shrublayer.Species_Scientific = qVEG_TreeSpeciesScientific.ID;
  "

  query_treelayer <- "
  SELECT Treelayer.IDPlots as plot_id,
  Treelayer.Species as name_id,
  qVEG_TreeSpecies.Value1 as name_nl,
  qVEG_TreeSpeciesScientific.Value1 as name_sc,
  Treelayer.Coverage as class_id
  FROM Treelayer
  LEFT JOIN qVEG_TreeSpecies ON Treelayer.Species = qVEG_TreeSpecies.ID
  LEFT JOIN qVEG_TreeSpeciesScientific ON Treelayer.Species_Scientific = qVEG_TreeSpeciesScientific.ID;
  "
  
  connect_db <- odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))

  herblayer_orig <- sqlQuery(connect_db, query_herblayer, stringsAsFactors = FALSE)
  shrublayer_orig <- sqlQuery(connect_db, query_shrublayer, stringsAsFactors = FALSE)
  treelayer_orig <- sqlQuery(connect_db, query_treelayer, stringsAsFactors = FALSE)

  odbcClose(connect_db)

   herblayer <- herblayer_orig %>%
     mutate(layer = "herblayer")

   shrublayer <- shrublayer_orig %>%
     mutate(layer = "shrublayer")

   treelayer <- treelayer_orig %>%
     mutate(layer = "treelayer")

  coverscales <- read_vc(file = "coverscales_mhq", root = "../../data")
   
  veglayers <- bind_rows(herblayer, shrublayer, treelayer) 
  
  colnames(veglayers) <- str_to_lower(colnames(veglayers))
  
  veglayers <- veglayers %>%
    filter(!is.na(name_id)) %>%
    mutate(coverscale_name = "Braun-Blanquet") %>%
    left_join(coverscales, by = c("coverscale_name", "class_id")) %>%
    select(plot_id, layer, name_nl, name_sc, coverscale_name, cover_description, cover_mean) %>%
    arrange(plot_id, layer, name_sc)
    
  return(veglayers)

}

get_date_foresthab <- function(db = db_fieldmap_foresthab){

  query_date_veg <- "SELECT
  IDPlots as plot_id,
  date_vegetation
  FROM Observer_date_veg"
  
   query_date_dendro <- "SELECT
  Observer_date_dendro.IDPlots as plot_id,
  Observer_date_dendro.date_dendro
  FROM Observer_date_dendro"

  connect_db <- odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))

  observer_date_veg <- sqlQuery(connect_db, query_date_veg)
  observer_date_dendro <- sqlQuery(connect_db, query_date_dendro)

  odbcClose(connect_db)
  
  observer_date <- observer_date_veg %>%
      full_join(observer_date_dendro, by =  "PLOT_ID")
  
  colnames(observer_date) <- str_to_lower(colnames(observer_date))
  
  observer_date_1 <- observer_date %>%
      group_by(plot_id) %>%
      summarise(date_vegetation = min(date_vegetation, na.rm = TRUE),
                date_dendro = min(date_dendro, na.rm = TRUE)) %>%
      ungroup() 
  
  return(observer_date_1)
}

get_coordinates_foresthab <- function(db = db_fieldmap_foresthab){

  query_coord <- "SELECT
  Plots_Forest_Inventory.Plotnr as plot_id,
  Plots_Forest_Inventory.X_m as x_measured,
  Plots_Forest_Inventory.Y_m as y_measured
  FROM Plots_Forest_Inventory"
  
  connect_db <- odbcDriverConnect(paste("DRIVER={Firebird/InterBase(r) driver};UID=SYSDBA;PWD=masterkey; DBNAME=", db))

  coordinates <- sqlQuery(connect_db, query_coord) %>%
      filter(!is.na(PLOT_ID))
  
  colnames(coordinates) <- str_to_lower(colnames(coordinates))

  odbcClose(connect_db)
  
  return(coordinates)
}
```


```


