# Query fieldmap openhab

```{r}
library(tidyverse)
library(RODBC)
```


## Database names

```{r}

db_fieldmap_foresthab <- "../../mhq_sample-admin_data/field-data/fieldmap/database_forest_2020-06-04/FIELDMAPDATA_BOSHAB_F_V2020_QC202004.FDB"
db_fieldmap_openhab <- "../../mhq_sample-admin_data/field-data/fieldmap/database_heath6510_2020-06-12/FIELDMAPDATA_MASTER_NAT2000_F_V5.FDB"
```

## Export 2020-06-12

```{r}

# sample_status
sample_status_openhab <- get_status_openhab()

sample_status_foresthab <- get_status_foresthab()

sample_status <- bind_rows(sample_status_openhab, 
                           sample_status_foresthab)

check <- sample_status %>%
    group_by(plot_id) %>%
    mutate(n = n()) %>%
    ungroup() %>%
    filter(n > 1)

sample_status <- sample_status %>%
    group_by(plot_id, sampling_unit_code) %>%
    summarise(date_status = min(date_status),
              status_fieldwork = unique(status_fieldwork),
              info_status_fieldwork = unique(info_status_fieldwork),
              remark = str_c(remark, collapse = "+")) %>%
    ungroup()

# type_observed

type_observed <- get_type_observed_openhab() %>%
    bind_rows(get_type_observed_foresthab())

check <-  type_observed %>%
    group_by(plot_id, type_observed_circle, type_observed_square, landuse) %>%
    mutate(n = n()) %>%
    ungroup() %>%
    filter(n > 1)

type_observed_corr <- type_observed %>%
    unique() %>%
    group_by(plot_id, type_observed_circle, type_observed_square, landuse) %>%
    summarise(segment_id = segment_id[1],
              type_observed_cover_circle = sum(type_observed_cover_circle)) %>%
    ungroup()

# veglayers

cover_veglayers <- get_cover_veglayers_openhab() %>%
    bind_rows(get_cover_veglayers_foresthab())

#species

cover_species <- get_cover_species_openhab() %>%
    bind_rows(get_cover_species_foresthab())

# structure_vars

structure_vars_heath <- get_measurements_heath_circle()

structure_vars_6510 <- get_measurements_6510_circle()

structure_vars <- bind_rows(structure_vars_heath, structure_vars_6510)

# date

date_assessment_forest <- get_date_foresthab() %>%
    mutate(date_assessment = pmin(date_vegetation, date_dendro))

date_assessment <- get_date_openhab(db_fieldmap_openhab_new) %>%
    bind_rows(date_assessment_forest)

# coordinates

coordinates  <- combine_db(get_coordinates_openhab(db_fieldmap_openhab_new),
                                    get_coordinates_openhab(db_fieldmap_openhab_old)) %>%
    bind_rows(get_coordinates_foresthab())

```


## Write result to .csv file

```{r}
setwd("../../mhq_sample-admin_data/field-data/fieldmap/")

if (!dir.exists(as.character(str_c("export_fieldmap", as.character(Sys.Date(),"%Y-%m-%d"), sep = "_")))) {
    
  dir.create(as.character(str_c("export_fieldmap", as.character(Sys.Date(),"%Y-%m-%d"), sep = "_")))  
    
}

setwd(str_c("export_fieldmap_", as.character(Sys.Date(),"%Y-%m-%d"), "/"))

write.csv2(sample_status, "sample_status.csv", row.names = FALSE)
write.csv2(type_observed_corr, "type_observed.csv", row.names = FALSE)
write.csv2(cover_veglayers, "cover_veglayers.csv", row.names = FALSE)
write.csv2(cover_species, "cover_species.csv", row.names = FALSE)
write.csv2(structure_vars, "structure_vars.csv", row.names = FALSE)
write.csv2(date_assessment, "date_assessment.csv", row.names = FALSE)
write.csv2(coordinates, "coordinates.csv", row.names = FALSE)

```

